name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Pull old Docker image
      run: docker pull docker.pkg.github.com/Richard87/php-base:latest && echo "pulled-maybeish"
      
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/Richard87/php-base:${{ github.sha }} --tag docker.pkg.github.com/Richard87/php-base:latest
    
    - name: Push image 1
      run: docker push docker.pkg.github.com/Richard87/php-base:${{ github.sha }} 
      
    - name: Push image 2
      run: docker push docker.pkg.github.com/Richard87/php-base:latest
